config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to:'pages#about'
  
  resources :articles

end

app/models/article.rb
class Article <ActiveRecord::Base
    
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    # makes sure that there is something in the title section of the article
    # title can be min 3 and max 30
    validates :description, presence: true, length: {minimum: 3, maximum: 300}
    
    
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController 
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
    def index
        @articles = Article.all
    end

   

    def new 
        @article = Article.new
    end 
    
    def edit
    end
    
    def update 
        if @article.update(article_params)
            # flash[:notice] = "Article was updated"
            redirect_to article_path(@article)
        else 
            render 'edit'
        end
    end
    
    def create
        @article = Article.new(article_params)
        if @article.save
            # flash[:notice] = "Article was successfully created"
            redirect_to articles_path
        else
            render 'new'
        end
    end
    
    def show 
    end

    def destroy 
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end
    
    

    
    private
    
    def set_article
         @article = Article.find(params[:id])
    end
    def article_params 
        params.require(:article).permit(:title, :description)
    end
    
    
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
    
    def home
        
    end
    
    def about
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the articles from being created</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @article do |g| %>
    <p>
        <%= g.label :title %> <br/>
        <!--the br tag moves the text field so that it is below the title>-->
        <%= g.text_field :title %>
    </p>
     <p>
        <%= g.label :description %> <br/>
        <%= g.text_area :description %>
     </p>
     <p>
         <%= g.submit %>
         <!--submit creates a button-->
     </p>
     
<% end %>

<%= link_to "Back", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Blog Posts</h1>
<!--<p>-->
<!--    <%= link_to "Create new article", new_article_path %>-->
<!--</p>-->


<table>
   
    
    
    
    <% @articles.each do |l| %>
        <div class="well">
        <!--<td><%= l.title %></td>-->
        <!--<td><%= l.description %></td>-->
        	<h3><%= l.title%></h3>
        	<p><%= l.description %></p>
        <!--<td><%= link_to "Edit", edit_article_path(l) %></td>-->
        <!--<td><%= link_to "Show", article_path(l) %></td>-->
        <%= link_to "Show", article_path(l), :class => 'btn btn-default' %>
        <!--<%= link_to "Edit", edit_article_path(l), :class => 'btn btn-default' %>-->
        <!--<td><%= link_to "Delete", article_path(l), method: :delete, data: {confirm: "Are you sure?"} %></td>-->
        </div>
    <% end %>

</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Article</h1>

<p>
    Title: <%= @article.title %>
</p>
<p>
    Description: <%= @article.description %>
</p>

 <%= link_to "Edit", edit_article_path, :class => 'btn btn-default' %>
 <%= link_to "Back", articles_path , :class => 'btn btn-default' %>
 <p>
     <td><%= link_to "Delete", article_path, method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %></td>
 </p>

app/views/layouts/_footer.html.erb
<div class="containter">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://www.alpha-blog-tester7.com">First Ruby App</a>
            by <a href="https://www.aplha-blog-testr7.com/">Danny Chung</a>
            
        </small>
        <nav>
            <ul>
            <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>

app/views/layouts/_navigation.html.erb
	<nav class="navbar navbar-default">
    	<div class = "container">
    	<div class = "navbar-header">
    		<button type = "button" class = "navbar-toggle collapsed"
    		data-toggle = "collapse" data-target= "#navbar"
    		aria-expanded = "false" aria-controls="navbar">
    		<span class = "sr-only">Toggle navigation</span>
    		<span class ="icon-bar"></span>
    		<span class ="icon-bar"></span>
    		<span class ="icon-bar"></span>
    	</button>
    	<a class = "navbar-brand" href="#">AlphaBlog </a>
    </div>
    <div id = "navbar" class="collapse navbar-collapse">
    	<ul class ="nav navbar-nav">
    		<!-- alwlows us to create a new option on navbar -->
    		<li><%= link_to "Home", root_path %></li>
    	</ul>
        
        <ul class ="nav navbar-nav">
    		<!-- alwlows us to create a new option on navbar -->
    		<li><%= link_to "Posts", articles_path %></li>
    	</ul>
    	
    	<ul class ="nav navbar-nav navbar-right">
    		<!-- creates the new option on the right to navigate -->
    		<li><%= link_to "Create Post", new_article_path%></li>
    	</ul>
        <ul class ="nav navbar-nav navbar-right">
            <!-- alwlows us to create a new option on navbar -->
            <li><%= link_to "About", about_path%></li>
        </ul>
    </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
<div class = "container">
	<!-- this creates a container around the text so its not so close to the right -->
    <%= yield %>
    </div>
</div>
<%= render'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Home', root_path%>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>ALPHA BLOG</h1>
    <%= link_to "Sign up now", "#", class: "btn btn-primary btn-lg" %>
</div>